services:
  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    depends_on:
      - db
    environment:
      - CONNECTION_STRING=Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};Encrypt=False;TrustServerCertificate=True;
    build:
      context: .
      dockerfile: UserService/Dockerfile

  productservice:
    image: ${DOCKER_REGISTRY-}productservice
    depends_on:
      - db
    environment:
      - CONNECTION_STRING=Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};Encrypt=False;TrustServerCertificate=True;
    build:
      context: .
      dockerfile: ProductService/Dockerfile

  cartservice:
    image: ${DOCKER_REGISTRY-}cartservice
    depends_on:
      - db
    environment:
      - CONNECTION_STRING=Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};Encrypt=False;TrustServerCertificate=True;
    build:
      context: .
      dockerfile: CartService/Dockerfile

  # orderservice:
  #   image: ${DOCKER_REGISTRY-}orderservice
  #   depends_on:
  #     - db
  #   environment:
  #     - CONNECTION_STRING=Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};Encrypt=False;TrustServerCertificate=True;
  #   build:
  #     context: .
  #     dockerfile: CartService/Dockerfile

  # paymentservice:
  #   image: ${DOCKER_REGISTRY-}paymentservice
  #   depends_on:
  #     - db
  #   environment:
  #     - CONNECTION_STRING=Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};Encrypt=False;TrustServerCertificate=True;
  #   build:
  #     context: .
  #     dockerfile: PaymentService/Dockerfile

  invoiceservice:
    image: ${DOCKER_REGISTRY-}invoiceservice
    depends_on:
      - db
    environment:
      - CONNECTION_STRING=Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};Encrypt=False;TrustServerCertificate=True;
    build:
      context: .
      dockerfile: InvoiceService/Dockerfile

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mssql_data:  